In [2]:
import torch

# Generator and Random Sampling

### Table of Contents

## Generators
1. [Class: torch.generator](#torch.generator)
## Random Sampling
1. [torch.seed](#torch.seed)
2. [torch.manual_seed](#torch.manual_seed)
3. [torch.initial_seed](#torch.initial_seed)
4. [torch.get_rng_state](#torch.get_rng_state)
5. [torch.set_rng_state](#torch.set_rng_state)
6. [torch.bernoulli](#torch.bernoulli)
7. [torch.multinomial](#torch.multinomial)
8. [torch.normal](#torch.normal)
9. [torch.poisson](#torch.poisson)
10. [torch.rand](#torch.rand)
11. [torch.randint](#torch.randint)
12. [torch.randn](#torch.randn)
13. [torch.randperm](#torch.randperm)

<a id="torch.generator"></a>

### 1. Class: torch.generator

`Class: torch.generator(device='cpu')`

Creates and returns a generator object that manages the state of the algorithm which produces pseudo random numbers. **Used as keyword argument in many in-place random sampling functions**.

In [3]:
g_cpu = torch.Generator()
g_cpu.device

device(type='cpu')

In [4]:
g_cuda = torch.Generator(device='cuda')
g_cuda.device

device(type='cuda')

In [7]:
# Returns the Generator state as torch.ByteTensor
g_cuda.get_state()

tensor([  1, 209, 156, 241,  48,  61,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0], dtype=torch.uint8)

In [8]:
# Returns the initial seed for generating random numbers
g_cuda.initial_seed()

67280421310721

In [9]:
# Sets the seed for generating random number. Returns a torch.Generator object. 
# Any 32-bit integer is a valid seed.
g_cuda.manual_seed(2147483647)

In [10]:
# Gets a non-deterministic random number from std::random_device or the 
# current time and uses it to seed a Generator.
g_cuda.seed()

1016705855477323

In [11]:
# Sets the Generator state
g_cpu = torch.Generator()
g_cpu_other = torch.Generator()
g_cpu.set_state(g_cpu_other.get_state())

<a id="torch.seed"></a>
### 1. torch.seed

`torch.seed()`

Sets the seed for generating random numbers to a non-deterministic random number. Returns a 64 bit number used to seed the RNG (random number generator).

In [14]:
torch.seed()

14995703360055430402

<a id="torch.manual_seed"></a>

### 2. torch.manual_seed

`torch.manual_seed(seed)`

Sets the seed for generating random numbers. Returns a torch.Generator object.

In [15]:
torch.manual_seed(42)

<a id="torch.initial_seed"></a>

### 3. torch.initial_seed

`torch.initial_seed()`

Returns the initial seed for generating random numbers as a Python long.

In [16]:
torch.initial_seed()

42

<a id="torch.get_rng_state"></a>

### 4. torch.get_rng_state

`torch.get_rng_state()`

Returns the random number generator state as torch.ByteTensor

In [19]:
torch.get_rng_state().shape

torch.Size([5056])

<a id="torch.set_rng_state"></a>

### 5. torch.set_rng_state

`torch.set_rng_state(new_state)`

Sets the random number generator state

In [39]:
torch.set_rng_state(g_cpu.get_state())

<a id="torch.bernoulli"></a>

### 6. torch.bernoulli

`torch.bernoulli(input, *, generator=None, out=None) -> Tensor`

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

The `input` tensor should be a tensor containing probabilities to be used for drawing the binary random number. Hence, all values in `input` have to be in the range: $0 \le input_i \le 1$.

The $i^{th}$ element of the output tensor will draw a value 1 according to the $i^{th}$ probability value given in `input`.

$$
out_i \sim Bernoulli(p=input_i)
$$

The returned `out` tensor only has values 0 or 1 and is of the same shape as `input`. 

In [52]:
a = torch.empty(3, 3).uniform_(0, 1) #generat a uniform random matrix with range [0, 1]
a

tensor([[0.2047, 0.9528, 0.3145],
        [0.9922, 0.6106, 0.8596],
        [0.1772, 0.9590, 0.0039]])

In [53]:
torch.bernoulli(a)

tensor([[1., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

In [54]:
a = torch.ones(3, 3) # probability of drawing "1" is 1
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [55]:
a = torch.zeros(3, 3) # probability of drawing "1" is 0
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

<a id="torch.multinomial"></a>

### 7. torch.multinomial

`torch.multinomial(input, num_sample, replacement=False, *, generator=None, out=None) -> LongTensor`

Returns a tensor where each row contains `num_samples` indices sampled from the multinomial probability distribution located in the corresponding row of tensor `input`.

Indices are ordered from left to right according to when each was sampled (first samples are placed in first column).

If `input` is a vector, `out` is a vector of size `num_samples`.

If `input` is a matrix with $m$ rows, `out` is an matrix of shape ($m \times num\_samples$).

If replacement is `True`, samples are drawn with replacement. If not, they are drawn without replacement, which means that when a sample index is drawn for a row, it cannot be drawn again for that row.

In [73]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float) #dtype must be float
torch.multinomial(weights, 2)

tensor([1, 2])

In [74]:
torch.multinomial(weights, 4) 

tensor([2, 1, 0, 3])

<a id="torch.normal"></a>

### 8. torch.normal

`torch.normal(mean, std, *, generator=None, out=None) -> Tensor`

Returns a tensor of random numbers drawn from seperate normal distributions whose mean and standard deviation are given.

The `mean` is tensor with the mean of each output element's normal distribution.
The `std` is a tensor with standard deviation of each output element's normal distribution. 

The shapes of `mean` and `std` don't need to match, but the total number of elements in each tensor need to be the same.

In [75]:
torch.arange(1, 0, -0.1)

tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])

In [76]:
torch.arange(1., 11.)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [77]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([0.3453, 3.1888, 3.5154, 2.9225, 4.8806, 6.4998, 6.8195, 8.0887, 9.1703,
        9.9702])

`torch.normal(mean=0.0, std, *. out=None) -> Tensor`

Similar to the function above, but the means are shared among all drawn elements.

In [78]:
torch.normal(mean=0.0, std=torch.arange(1, 0, -0.1))

tensor([-1.1380, -0.3907,  0.0495,  0.3620, -0.3351,  0.0270, -0.3812, -0.2307,
        -0.2955, -0.0478])

`torch.normal(mean, std=1.0, *, out=None) -> Tensor`

Similar to the function above, but the standard deviations are shared among all drawn elements.

In [80]:
torch.normal(mean=torch.arange(1., 6.), std=1.0)

tensor([1.4169, 3.2619, 2.6796, 4.2100, 4.7874])

`torch.normal(mean, std, size, *, out=None) -> Tensor`

Similar to the function above, but the means and standard deviations are shared among all drawn elements. The resulting tensor has size given by `size`

In [81]:
torch.normal(2, 3, size=(1,4))

tensor([[-2.5498,  4.8837,  4.9624,  2.6168]])

<a id="torch.poisson"></a>

### 9. torch.poisson

`torch.poisson(input, generator=None) -> Tensor`

Returns a tensor of the same size as `input` with each element sampled from a Poisson distribution with rate parameter given by the corresponding element in `input` i.e:

$$
out_i \sim Poisson(input_i)
$$

`input` must be non-negative.


In [89]:
rates = torch.rand(4, 4) * 5 # rate parameters between 0 and 5
torch.poisson(rates)

tensor([[3., 4., 4., 3.],
        [6., 0., 3., 0.],
        [1., 2., 1., 0.],
        [0., 4., 2., 1.]])

<a id="torch.rand"></a>

### 10. torch.rand

`torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor`
            
Returns a tensor filled with random numbers from a uniform distribution on the interval $[0, 1)$.

The shape of tensor is defined by the variable argument `size`

In [90]:
torch.rand(4)

tensor([0.3450, 0.7429, 0.8334, 0.2884])

In [91]:
torch.rand(2, 3)

tensor([[0.1206, 0.7434, 0.4270],
        [0.3401, 0.9584, 0.6717]])

`torch.rand_like(input, *, dtype=None, layout=None, device=None,requires_grad=False, memory_format=torch.preserve_format) → Tensor`

Returns a tensor with the same size as `input` that is filled with random numbers from a uniform distribution on the interval $[0, 1)$. `torch.rand_like(input)` is equivalent to `torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)`.

<a id="torch.randint"></a>

### 11. torch.randint

`torch.randint(low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor`

Returns a tensor filled with random integers generated uniformly between `low` (inclusive) and `high` (exclusive).

The shape of the tensor is defined by the variable argument `size`. 

In [92]:
torch.randint(3, 5, (3,))

tensor([4, 3, 3])

In [94]:
torch.randint(10, (2,2))

tensor([[5, 8],
        [9, 0]])

In [95]:
torch.randint(3, 10, (2,2))

tensor([[4, 9],
        [3, 4]])

also `torch.randint_like(input, low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor`

Returns a tensor with the same shape as Tensor input filled with random integers generated uniformly between low (inclusive) and high (exclusive).

<a id="torch.randn"></a>

### 12. torch.randn

`torch.randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor`

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal dist).

$$
out_i \sim \mathcal{N}(0,\,1)
$$

The shape of the tensor is defined by the variable argument `size`.

In [96]:
torch.randn(4)

tensor([ 0.3194,  0.8025,  1.8042, -1.4461])

In [97]:
torch.randn(2,3)

tensor([[ 0.4332,  0.6514, -0.1746],
        [ 0.6550,  0.6287, -3.2408]])

also `torch.randn_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor`

Returns a tensor with the same size as input that is filled with random numbers from a normal distribution with mean 0 and variance 1. `torch.randn_like(input)` is equivalent to `torch.randn(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)`.

<a id="torch.randperm"></a>

### 13. torch.randperm

`torch.randperm(n, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor`

Returns a random permutation of integers from `0` to `n - 1`

In [98]:
torch.randperm(4)

tensor([2, 3, 1, 0])

In [99]:
torch.randperm(10)

tensor([5, 7, 3, 6, 0, 2, 8, 4, 1, 9])