In [1]:
import torch

# Pointwise Ops

1. [torch.abs](#torch.abs)
2. [torch.ascos](#torch.acos)
3. [torch.acosh](#torch.acosh)
4. [torch.add](#torch.add)
5. [torch.addcdiv](#torch.addcdiv)
6. [torch.addcmul](#torch.addcmul)
7. [torch.angle](#torch.angle)
8. [torch.asin](#torch.asin)
9. [torch.asinh](#torch.asinh)
10. [torch.atan](#torch.atan)
11. [torch.atanh](#torch.atanh)
12. [torch.atan2](#torch.atan2)
13. [torch.bitwise_not](#torch.bitwise_not)
14. [torch.bitwise_and](#torch.bitwise_and)
15. [torch.bitwise_or](#torch.bitwise_or)
16. [torch.bitwise_xor](#torch.bitwise_xor)
17. [torch.bitwise_left_shift](#torch.bitwise_left_shift)
18. [torch.bitwise_right_shift](#torch.bitwise_right_shift)
19. [torch.ceil](#torch.ceil)
20. [torch.clamp](#torch.clamp)
21. [torch.clip](#torch.clip)
22. [torch.conj_physical](#torch.conj_physical)
23. [torch.copysign](#torch.copysign)
24. [torch.cos](#torch.cos)
25. [torch.cosh](#torch.cosh)
26. [torch.deg2rad](#torch.deg2rad)
27. [torch.div](#torch.div)
28. [torch.exp](#torch.exp)
29. [torch.fake_quantize_per_channel_affine](#torch.fake_quantize_per_channel_affine)
30. [torch.fake_quantize_per_tenbsor_affine](#torch.fake_quantize_per_tensor_affine)

<a id="torch.abs"></a>

### 1. torch.abs

`torch.abs(input, *, out=None) -> Tensor`

Computes the absolute value of each element in `input`

$$
out_i = |input_i|
$$


In [2]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

`torch.absolute(input, *, out=None)` is alias for `torch.abs()`

<a id="torch.acos"></a>

### 2. torch.acos

`torch.acos(input, *, out=None) -> None`

Computes the inverse cosine of each element in `input`

$$
out_i = cos^{-1}(input_i)
$$

In [3]:
a = torch.randn(4)
a

tensor([ 1.0813, -0.7721,  0.9082,  0.9951])

In [4]:
torch.acos(a)

tensor([   nan, 2.4530, 0.4318, 0.0987])

<a id="torch.acosh"></a>

`torch.acosh(input, *, out=None) -> Tensor`

Returns a new tensor with inverse hyperbollic cosine of the element of `input`

$$
out_i = cosh^{-1}(input_i)
$$


In [5]:
a = torch.randn(4).uniform_(1, 2)
a

tensor([1.7691, 1.9889, 1.6800, 1.2829])

In [6]:
torch.acosh(a)

tensor([1.1720, 1.3105, 1.1086, 0.7355])

<a id="torch.add"></a>

### 3. torch.add

`torch.add(input, other, *, alpha=1, out=None) -> Tensor`

Adds `other`, scaled by `alpha`, to `input`.

$$
out_i = input_i + alpha \times other_i
$$

Supports broadcasting to a common shape, type promotion, and integer, float, and complex inputs.

In [7]:
a = torch.randn(4)
a

tensor([-0.7448, -1.1259, -1.6386,  0.7319])

In [8]:
torch.add(a, 20)

tensor([19.2552, 18.8741, 18.3614, 20.7319])

In [9]:
b = torch.randn(4)
b

tensor([ 0.1646, -1.4158,  0.0566, -0.7817])

In [10]:
c = torch.randn(4, 1)
c

tensor([[1.8293],
        [1.0155],
        [1.3555],
        [0.8046]])

In [11]:
torch.add(b, c, alpha=10)

tensor([[18.4579, 16.8774, 18.3498, 17.5115],
        [10.3197,  8.7392, 10.2116,  9.3733],
        [13.7196, 12.1391, 13.6115, 12.7732],
        [ 8.2111,  6.6307,  8.1031,  7.2648]])

<a id="torch.addcdiv"></a>

### 4. torch.addcdiv

`torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None) -> Tensor`

Performs the elemnt-wise division of `tensor1` by `tensor2`, miltples the result by the scalar `value` and adds it to `input`.

$$
out_i = input_i + value \times \frac{tensor1_i}{tensor2_i}
$$

The shaoes of `input`, `tensor1`, and `tensor2` must be broadcastable.

In [13]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[-0.5994, -0.1661, -0.4045],
        [ 0.8157, -0.1185, -0.3633],
        [-1.7717, -0.2056, -0.4385]])

<a id="torch.angle"></a>

### 5. torch.angle

`torch.angle(input, *, out=None) -> Tensor`

Computes the element-wise angle (in radians) of the given `input` tensor.

$$
out_i = angle(input_i)
$$

In [14]:
torch.angle(torch.tensor([-1 - 1j, -2 - 2j, 3 - 3j]))*180/3.14159

tensor([-135.0001, -135.0001,  -45.0000])

<a id="torch.asin"></a>

### 5. torch.asin

`torch.asin(input, *, out=None) -> Tensor`

Returns a new tensor with arcsine of the elements of `input`.

$$
out_i = sin^{-1}(input_i)
$$

In [15]:
a = torch.randn(4)
a

tensor([ 0.8824,  0.2929, -0.2238, -1.5031])

In [16]:
torch.asin(a)

tensor([ 1.0808,  0.2972, -0.2257,     nan])

`torch.arcsin(input, *, out=None)` is an alias for `torch.asin()`

<a id="torch.asinh"></a>

### 6. torch.asinh

`torch.asinh(input, *, out=None) -> Tensor`

Returns a new tensor with the inverse hyperbollic sine of the elements of `input`

$$
out_i = sinh^{-1}(input_i)
$$

In [17]:
a = torch.randn(4)
a

tensor([1.0690, 1.1511, 0.7242, 0.1606])

In [18]:
torch.asinh(a)

tensor([0.9293, 0.9843, 0.6723, 0.1599])

<a id="torch.atan"></a>

### 7. torch.atan

`torch.atan(input, *, out=None) -> Tensor`

Returns a new tensor with arctangent of the elements of `input`

$$
out_i = tan^{-1}(input_i)
$$

In [19]:
a = torch.randn(4)
a

tensor([-0.6358,  2.0017,  0.0516, -0.8333])

In [20]:
torch.atan(a)

tensor([-0.5663,  1.1075,  0.0516, -0.6947])

`torch.arctan()` is an alias for `torch.atan`

<a id="torch.atanh"></a>

### 8. torch.atanh

`torch.atanh(input, *, out=None) -> Tensor`

Returns a new tensor with the inverse **hyperbolic** tangent of the elements of `input`.

$$
out_i = tanh^{-1}(input_i)
$$

In [21]:
a = torch.randn(4).uniform_(-1, 1)
a

tensor([ 0.8947,  0.4414,  0.1946, -0.0275])

In [22]:
torch.atanh(a)

tensor([ 1.4452,  0.4739,  0.1971, -0.0275])

`torch.arctanh` is alias for torch.atanh().

<a id="torch.atan2"></a>

### 9. torch.atan2 

`torch.atan2(input, other, *, out=None) -> Tensor`

Element-wise arctangent of $input_i/other_i$ with consideration of the quadrant. Returns a new tensor with the signed angles in randians between vector ($other_i, input_i$) and vector (1, 0).

Note: $other_i$, the second parameter, is the x-coordinate, while $input_i$, the first parameter is the y-coordinate.

The shape of `input` and `other` must be broadcastable.

In [23]:
a = torch.randn(4)
a

tensor([-0.7967,  0.1279, -0.6264, -0.1719])

In [24]:
torch.atan2(a, torch.randn(4))

tensor([-2.7700,  2.8599, -1.9817, -1.1369])

`torch.arctan2(input, other, *, out=None)` is alias for `torch.atan2()`